# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d073975ed9547be1d54ae0deefc00cdde5c7b343ef99bada0a4b8e39558f7534c13ca88dc2ac48cb97cf533edbab9139407eff4196819ca298d15e24138af2c

test:
  secret_key_base: 784897a9b6164043874f75722d78baa3ba45357b176efd320db08ffc55f2029b820fc19beeb49afe3e116d11ab35f765942ddc2b0bc96564635dba6198729864

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
